import {at, defineMigration, set, unset} from 'sanity/migrate'

import {TAG_SEED, tagId} from '../create-tag-documents'

/**
 * Step 2 of 2. Rewrite `photo.tags` and `gallery.tag` from strings into references.
 *
 * **Run `create-tag-documents` first**, in a separate `sanity migrations run`, and let it
 * finish. See the note there: transactions are submitted concurrently, so a reference written
 * in the same run that creates its target can fail on integrity partway through.
 *
 * ## Drafts are included, and must be
 *
 * `sanity migrations run` streams `/data/export/<dataset>` without `drafts=false`, so drafts
 * come through by default and `documentTypes` matches on `_type`, which a draft shares with its
 * published twin. Do not add a filter to exclude them. `development` holds
 * `drafts.gallery-mexico-2022`, and a draft left holding a string in a field the schema now
 * types as a reference renders as a broken field in the Studio — and the next `npm run promote`
 * carries it into `production` unchanged.
 *
 * Expected dry-run scope: **19 photos + 5 published galleries + 1 draft = 25 documents.** If the
 * draft is missing from the output, stop — that means drafts are not being streamed and the
 * paragraph above is wrong for this CLI version.
 *
 * ## Idempotent, and loud about the one thing it cannot handle
 *
 * Only *string* members are converted, so a document already migrated holds objects, matches
 * nothing, and is left alone — a second run is a no-op. A value with no tag document would
 * otherwise be patched in as a strong reference to something that does not exist and fail the
 * mutation mid-run, so it throws instead, naming the document and the value. That fires during
 * the dry run, before anything has been written.
 */
const KNOWN = new Set(TAG_SEED.map((entry) => entry.slug))

const ref = (slug: string) => ({_type: 'reference' as const, _ref: tagId(slug)})

/**
 * The one failure this migration can hit, raised by both branches below.
 *
 * A photo and a gallery fail for exactly the same reason — a stored value with no matching tag
 * document — and the remedy is the same for both: add it to `TAG_SEED` and re-run
 * `create-tag-documents`. Two anonymous `Error`s would have made that one situation look like
 * two, and a caller wanting to tell "this value is unmappable" apart from a transport failure
 * would have had to match on message text.
 */
class UnmappableTagValueError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'UnmappableTagValueError'
  }
}

export default defineMigration({
  title: 'Rewrite photo.tags and gallery.tag as references to tag documents',
  documentTypes: ['photo', 'gallery'],

  migrate: {
    document(doc) {
      if (doc._type === 'photo') {
        const tags = doc.tags
        if (!Array.isArray(tags)) return

        const strings = tags.filter((value): value is string => typeof value === 'string')
        if (strings.length === 0) return

        const orphan = strings.find((value) => !KNOWN.has(value))
        if (orphan) {
          throw new UnmappableTagValueError(
            `${doc._id} carries the tag "${orphan}", which has no tag document. ` +
              'Add it to TAG_SEED in migrations/create-tag-documents and run that migration again.',
          )
        }

        // `set` and not `insert`: the whole array is replaced, so mixed old/new content cannot
        // survive. `_key`s are generated by the runner (`autoGenerateArrayKeys`).
        return at('tags', set(strings.map(ref)))
      }

      if (doc._type === 'gallery') {
        if (typeof doc.tag !== 'string') return

        // The empty string is the cleared-but-not-unset state the old string field allowed, and
        // the one `queries/shots.ts` needed a two-term guard against because `defined("")` is
        // true. A reference has no such state, so this is where that whole class of bug is
        // retired: it becomes an unset field, which is the only empty a reference has.
        if (doc.tag === '') return at('tag', unset())

        if (!KNOWN.has(doc.tag)) {
          throw new UnmappableTagValueError(
            `${doc._id} points at the tag "${doc.tag}", which has no tag document.`,
          )
        }

        return at('tag', set(ref(doc.tag)))
      }
    },
  },
})
