/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type ProseText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    url: string;
    _type: "hyperlink";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type PhotoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "photo";
};

export type PostPhoto = {
  _type: "postPhoto";
  photo: PhotoReference;
};

export type Link = {
  _type: "link";
  label: string;
  url: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  byline: string;
  description: string;
  shareImage: PhotoReference;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  intro?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          url: string;
          _type: "hyperlink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & PostPhoto)
  >;
};

export type WritingPage = {
  _id: string;
  _type: "writingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  intro?: string;
};

export type GalleryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "gallery";
};

export type ShotsPage = {
  _id: string;
  _type: "shotsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  intro?: string;
  photos: Array<
    {
      _key: string;
    } & PhotoReference
  >;
  galleries?: Array<
    {
      _key: string;
    } & GalleryReference
  >;
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introHeading?: string;
  introPhoto: PhotoReference;
  intro: ProseText;
  blurb: ProseText;
  featuredWriting: ArrayOf<PostReference | ArticleReference>;
  featuredTitle: ProseText;
  featuredSubtitle: ProseText;
  featuredPhotos: Array<
    {
      _key: string;
    } & PhotoReference
  >;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  publication: string;
  url: string;
  publishedAt: string;
  summary?: string;
  coverPhoto?: PhotoReference;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary?: string;
  coverPhoto?: PhotoReference;
  publishedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "blockquote";
        listItem?: never;
        markDefs?: Array<{
          url: string;
          _type: "hyperlink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & PostPhoto)
  >;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  preset: "grid" | "stack";
  photos: Array<
    {
      _key: string;
    } & PhotoReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Photo = {
  _id: string;
  _type: "photo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
  caption?: string;
  place?: string;
  dateTaken?: string;
  tags?: Array<
    "street" | "portrait" | "landscape" | "architecture" | "water" | "night"
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProseText
  | PhotoReference
  | PostPhoto
  | Link
  | SiteSettings
  | ContactPage
  | AboutPage
  | WritingPage
  | GalleryReference
  | ShotsPage
  | PostReference
  | ArticleReference
  | HomePage
  | Article
  | Post
  | Slug
  | Gallery
  | SanityImageAssetReference
  | Photo
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/app/queries/about.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "aboutPage"][0]{    title,    body[]{      ...,      _type == "postPhoto" => { photo->{   _id,  alt,  caption,  "asset": image.asset->{    url,    "lqip": metadata.lqip,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  } } }    }  }
export type ABOUT_QUERY_RESULT = {
  title: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          url: string;
          _type: "hyperlink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "postPhoto";
        photo: {
          _id: string;
          alt: string;
          caption: string | null;
          asset: {
            url: string;
            lqip: string | null;
            width: number | null;
            height: number | null;
          };
        };
      }
  >;
} | null;

// Source: ../web/app/queries/home.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage"][0]{    title,    introHeading,    introPhoto->{   _id,  alt,  caption,  "asset": image.asset->{    url,    "lqip": metadata.lqip,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  } },    intro,    blurb,    featuredWriting[]->{      _id,      _type,      title,      publishedAt,      summary,      coverPhoto->{   _id,  alt,  caption,  "asset": image.asset->{    url,    "lqip": metadata.lqip,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  } },      _type == "article" => { url, publication },      _type == "post" => { "slug": slug.current }    },    featuredTitle,    featuredSubtitle,    featuredPhotos[]->{   _id,  alt,  caption,  "asset": image.asset->{    url,    "lqip": metadata.lqip,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  } }  }
export type HOME_QUERY_RESULT = {
  title: string;
  introHeading: string | null;
  introPhoto: {
    _id: string;
    alt: string;
    caption: string | null;
    asset: {
      url: string;
      lqip: string | null;
      width: number | null;
      height: number | null;
    };
  };
  intro: ProseText;
  blurb: ProseText;
  featuredWriting: Array<
    | {
        _id: string;
        _type: "article";
        title: string;
        publishedAt: string;
        summary: string | null;
        coverPhoto: {
          _id: string;
          alt: string;
          caption: string | null;
          asset: {
            url: string;
            lqip: string | null;
            width: number | null;
            height: number | null;
          };
        } | null;
        url: string;
        publication: string;
      }
    | {
        _id: string;
        _type: "post";
        title: string;
        publishedAt: string;
        summary: string | null;
        coverPhoto: {
          _id: string;
          alt: string;
          caption: string | null;
          asset: {
            url: string;
            lqip: string | null;
            width: number | null;
            height: number | null;
          };
        } | null;
        slug: string;
      }
  >;
  featuredTitle: ProseText;
  featuredSubtitle: ProseText;
  featuredPhotos: Array<{
    _id: string;
    alt: string;
    caption: string | null;
    asset: {
      url: string;
      lqip: string | null;
      width: number | null;
      height: number | null;
    };
  }>;
} | null;

// Source: ../web/app/queries/writing.ts
// Variable: WRITING_QUERY
// Query: {    "page": *[_type == "writingPage"][0]{ title, intro },    "items": *[_type in ["post", "article"]] | order(publishedAt desc){      _id,      _type,      title,      publishedAt,      summary,      coverPhoto->{   _id,  alt,  caption,  "asset": image.asset->{    url,    "lqip": metadata.lqip,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  } },      _type == "article" => { url, publication },      _type == "post" => { "slug": slug.current }    }  }
export type WRITING_QUERY_RESULT = {
  page: {
    title: string;
    intro: string | null;
  } | null;
  items: Array<
    | {
        _id: string;
        _type: "article";
        title: string;
        publishedAt: string;
        summary: string | null;
        coverPhoto: {
          _id: string;
          alt: string;
          caption: string | null;
          asset: {
            url: string;
            lqip: string | null;
            width: number | null;
            height: number | null;
          };
        } | null;
        url: string;
        publication: string;
      }
    | {
        _id: string;
        _type: "post";
        title: string;
        publishedAt: string;
        summary: string | null;
        coverPhoto: {
          _id: string;
          alt: string;
          caption: string | null;
          asset: {
            url: string;
            lqip: string | null;
            width: number | null;
            height: number | null;
          };
        } | null;
        slug: string;
      }
  >;
};

// Source: ../web/app/queries/writing.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    publishedAt,    summary,    body[]{      ...,      _type == "postPhoto" => { photo->{   _id,  alt,  caption,  "asset": image.asset->{    url,    "lqip": metadata.lqip,    "width": metadata.dimensions.width,    "height": metadata.dimensions.height  } } }    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string;
  publishedAt: string;
  summary: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "normal";
        listItem?: never;
        markDefs?: Array<{
          url: string;
          _type: "hyperlink";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "postPhoto";
        photo: {
          _id: string;
          alt: string;
          caption: string | null;
          asset: {
            url: string;
            lqip: string | null;
            width: number | null;
            height: number | null;
          };
        };
      }
  >;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "aboutPage"][0]{\n    title,\n    body[]{\n      ...,\n      _type == "postPhoto" => { photo->{ \n  _id,\n  alt,\n  caption,\n  "asset": image.asset->{\n    url,\n    "lqip": metadata.lqip,\n    "width": metadata.dimensions.width,\n    "height": metadata.dimensions.height\n  }\n } }\n    }\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_type == "homePage"][0]{\n    title,\n    introHeading,\n    introPhoto->{ \n  _id,\n  alt,\n  caption,\n  "asset": image.asset->{\n    url,\n    "lqip": metadata.lqip,\n    "width": metadata.dimensions.width,\n    "height": metadata.dimensions.height\n  }\n },\n    intro,\n    blurb,\n    featuredWriting[]->{\n      _id,\n      _type,\n      title,\n      publishedAt,\n      summary,\n      coverPhoto->{ \n  _id,\n  alt,\n  caption,\n  "asset": image.asset->{\n    url,\n    "lqip": metadata.lqip,\n    "width": metadata.dimensions.width,\n    "height": metadata.dimensions.height\n  }\n },\n      _type == "article" => { url, publication },\n      _type == "post" => { "slug": slug.current }\n    },\n    featuredTitle,\n    featuredSubtitle,\n    featuredPhotos[]->{ \n  _id,\n  alt,\n  caption,\n  "asset": image.asset->{\n    url,\n    "lqip": metadata.lqip,\n    "width": metadata.dimensions.width,\n    "height": metadata.dimensions.height\n  }\n }\n  }\n': HOME_QUERY_RESULT;
    '\n  {\n    "page": *[_type == "writingPage"][0]{ title, intro },\n    "items": *[_type in ["post", "article"]] | order(publishedAt desc){\n      _id,\n      _type,\n      title,\n      publishedAt,\n      summary,\n      coverPhoto->{ \n  _id,\n  alt,\n  caption,\n  "asset": image.asset->{\n    url,\n    "lqip": metadata.lqip,\n    "width": metadata.dimensions.width,\n    "height": metadata.dimensions.height\n  }\n },\n      _type == "article" => { url, publication },\n      _type == "post" => { "slug": slug.current }\n    }\n  }\n': WRITING_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    publishedAt,\n    summary,\n    body[]{\n      ...,\n      _type == "postPhoto" => { photo->{ \n  _id,\n  alt,\n  caption,\n  "asset": image.asset->{\n    url,\n    "lqip": metadata.lqip,\n    "width": metadata.dimensions.width,\n    "height": metadata.dimensions.height\n  }\n } }\n    }\n  }\n': POST_QUERY_RESULT;
  }
}
